trigger:
    tags:
        include:
            - refs/tags/v*
            - refs/remotes/origin/tags/v*

pool:
    vmImage: 'ubuntu-latest'


# variables for package building
# -------------------------------------------------
variables:
    -   phpVersion: 7.3
    -   packageName: cloud-cron-bundle
    -   archivingFilePath: $(Build.ArtifactStagingDirectory)/$(packageName)-build-$(Build.SourceVersion)-$(Build.BuildNumber).zip
    -   targetPath: de-sit-phpc-php-local/php/bundles/$(packageName)/commits/$(Build.SourceVersion)/


# Jobs and steps
# -------------------------------------------------
jobs:
    -   job: publish_composer_package
        displayName: 'Validate, archive and publish'
        steps:
            -   template: steps/set-php-path.yml
            -   template: steps/validate-composer-package-version.yml
            -   template: steps/generate-auth-json.yml

            -   task: CmdLine@2
                displayName: 'Archiving files'
                inputs:
                    script: |
                        echo "Archiving files to zip-container and exclude git-files"
                        cd $(Build.Repository.LocalPath)
                        zip -r $(archivingFilePath) . -x "*.git*"
                        echo
                        stat $(archivingFilePath)
                    workingDirectory: '$(Build.Repository.LocalPath)'
                enabled: true

            -   task: JFrog.jfrog-artifactory-vsts-extension.artifactory-generic-upload.ArtifactoryGenericUpload@2
                displayName: 'Artifactory Generic Upload'
                inputs:
                    artifactoryService: 'Schwarz IT Artifactory'
                    fileSpec: |
                        {
                          "files": [
                            {
                              "pattern": "$(archivingFilePath)",
                              "target": "$(targetPath)"
                            }
                          ]
                        }
                    collectBuildInfo: true
                    includeEnvVars: true
                enabled: true

            -   template: steps/build-info.yml
